# Change these first
owner: 10ego # Your GitHub organization or username, where this repository lives
repo: HREup # The name of this repository

sites:
  - name: The Drug and Health Products Register
    url: https://hpr-rps.hres.ca
  - name: Canada Food Guide
    url: https://food-guide.canada.ca
  - name: COVID Vaccine Portal
    url: https://covid-vaccine.canada.ca
  - name: Controlled Vocabulary
    url: https://cv.hres.ca
  - name: Clinical Trials Search
    url: https://health-products.canada.ca/ctdb-bdec/index-eng.jsp
  - name: Drug Products Database
    url: https://health-products.canada.ca/dpd-bdpp/
  - name: Canadian Nutrient File
    url: https://health-products.canada.ca/cnf-fce/
  - name: LNHPD search
    url: https://health-products.canada.ca/lnhpd-bdpsnh/
  - name: Medical Devices Active License Listing
    url: https://health-products.canada.ca/mdall-limh/
  - name: Medical Devices Establishment License Listing
    url: https://health-products.canada.ca/mdel-leim/
  - name: Notice of Compliance search
    url: https://health-products.canada.ca/noc-ac/
  - name: Veterinary Health Products - Notification Program
    url: https://health-products.canada.ca/vhp-psa/en
  - name: Product Monograph PDFs
    url: $PDF_PM
  - name: Reference Listing of Accepted Construction Materials, Packaging Materials and Non-Food Chemical Products Database
    url: https://fpia.hres.ca
  - name: Canada Vigilance Consumer Dashboard
    url: https://health-products.canada.ca/adverse-reaction/
  - name: Consumer App Push Notification Service
    url: $CVT_PNS

assignees:
  - 10ego
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /HREup
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: HREup
  introTitle: "**HREup** is an open-source uptime monitor and status page for HRE applications, powered entirely by GitHub using Upptime."
  introMessage: This is a github page which uses **real-time** data from the [GitHub repository](https://github.com/10ego/HREup). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
